---
version: "3"

dotenv: [".env"]

env:
  DOCKER_GID:
    sh: stat -c '%g' /var/run/docker.sock
  HOSTNAME:
    sh: hostname
  ROOT_DIR: "{{.ROOT_DIR}}"

includes:
  git:
    taskfile: .taskfiles/git.tasks.yml
    optional: true
    internal: true

  docker:
    taskfile: .taskfiles/docker.tasks.yml
    optional: true
    internal: true

tasks:
  default:
    cmds:
      - task -l
    silent: true

  deploy:
    desc: Deploy containers
    cmds:
      - task: docker:compose:deploy
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"

  deploy:host:
    desc: Deploy a host container configuration
    cmds:
      - task: docker:compose:deploy
        vars:
          CLI_ARGS: "compose/{{.HOSTNAME}}.yml"

  destroy:
    desc: Destroy containers
    cmds:
      - task: docker:compose:destroy
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"

  destroy:host:
    desc: Destroy a host container configuration
    cmds:
      - task: docker:compose:destroy
        vars:
          CLI_ARGS: "compose/{{.HOSTNAME}}.yml"

  lint:
    desc: Check the syntax on scripts
    cmds:
      - shellcheck "{{.ROOT_DIR}}/scripts/*.sh"

  logs:
    desc: "Check a container's logs"
    cmds:
      - task: docker:compose:logs
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"

  setup:
    desc: "Configure repository for use"
    cmds:
      - "{{.ROOT_DIR}}/scripts/configure_templates.sh"

  update:
    desc: "Update repo"
    cmds:
      - rm -rf .taskfiles
      - git restore .
      - git clone https://github.com/frozenfoxx/taskfiles.git .taskfiles
      - git pull --rebase

  upgrade:
    desc: "Upgrade a container"
    cmds:
      - task: docker:compose:upgrade
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"

  upgrade:host:
    desc: "Upgrade all containers for a host"
    cmds:
      - task: docker:compose:upgrade
        vars:
          CLI_ARGS: "compose/{{.HOSTNAME}}.yml"

  validate:
    desc: "Validate a Docker Compose configuration"
    cmds:
      - task: docker:compose:validate
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"

  validate:host:
    desc: "Validate a host container configuration"
    cmds:
      - task: docker:compose:validate
        vars:
          CLI_ARGS: "compose/{{.HOSTNAME}}.yml"