services:
  cross-seed:
    image: ghcr.io/cross-seed/cross-seed@sha256:93418ffe42ccda770706b10294b46f8642bd1f6da4ca57b4c11b1b220f54e3d3 # v6.13.7
    container_name: cross-seed
    restart: unless-stopped
    command: daemon
    user: "1028:50" # 'staff' user/group; cross-seed has no PUID/PGID support
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - cross-seed-config:/config
      - cross-seed-data:/data
    ports:
      - 2468:2468
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki

volumes:
  cross-seed-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/cross-seed/config"

  cross-seed-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${MEDIA_HOST},nolock,soft,rw"
      device: ":/volume1/Media/downloads"