---
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    environment:
      - PUID=1028 # 'staff' user
      - PGID=50 # 'staff' group
      - TZ=America/Los_Angeles
      - JELLYFIN_PublishedServerUrl=https://jellyfin.${NETWORK_DOMAIN-bricksandblocks.net}
      # Optional hardware transcoding mods, see https://mods.linuxserver.io/?mod=jellyfin
      #- DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      # - jellyfin-data:/config
      - ${LOCAL_PREFIX-/local}/jellyfin/config:/config
      - jellyfin-music:/data/Music:ro
      - jellyfin-videos:/data/Videos:ro
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki

volumes:
  # jellyfin-data:
  #   driver: local
  #   driver_opts:
  #     type: nfs
  #     o: "addr=${DATA_HOST},nolock,soft,rw"
  #     device: ":/volume1/Docker/jellyfin/library"

  jellyfin-music:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${MEDIA_HOST},nolock,soft,ro"
      device: ":/volume1/Media/Music"

  jellyfin-videos:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${MEDIA_HOST},nolock,soft,ro"
      device: ":/volume1/Media/Videos"
