---
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=1028 # 'staff' user
      - PGID=50 # 'staff' group
      - TZ=America/Los_Angeles
    volumes:
      #- lidarr-config:/config
      - ${LOCAL_PREFIX-/local}/lidarr/config:/config
      - lidarr-data:/data
    ports:
      - 8786:8686
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki

volumes:
  #lidarr-config:
  #  driver: local
  #  driver_opts:
  #    type: nfs
  #    o: "addr=${DATA_HOST},nolock,soft,rw"
  #    device: ":/volume1/Docker/lidarr/config"

  lidarr-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${MEDIA_HOST},nolock,soft,rw"
      device: ":/volume1/Media"