---
#networks:
#  notifiarr:
#    name: notifiarr
#    external: true

services:
  notifiarr:
    image: golift/notifiarr
    container_name: notifiarr
    hostname: notifiarr
    restart: unless-stopped
    user: 1028:50 # UID=1028, 'staff' user, GID=50, 'staff' group
#    networks: [notifiarr]
    security_opt: ['no-new-privileges:true']
    #environment:
      #- DN_API_KEY=${NOTIFIARR_API_KEY}
    ports:
      - "5454:5454"
    volumes:
      - notifiarr-config:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki

volumes:
  notifiarr-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/notifiarr/config"