services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - PLEX_CLAIM=${PLEX_CLAIM} #optional
      - TZ=America/Los_Angeles
      - VERSION=docker
    volumes:
      #- plex-data:/config
      - plex-music:/data/Music:ro
      - plex-videos:/data/Videos:ro
      - ${LOCAL_PREFIX-/local}/plex/config:/config
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki

volumes:
  #plex-data:
  #  driver: local
  #  driver_opts:
  #    type: nfs
  #    o: "addr=${DATA_HOST},nolock,soft,rw"
  #    device: ":/volume1/Docker/plex/config"

  plex-music:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${MEDIA_HOST},nolock,soft,ro"
      device: ":/volume1/Media/Music"

  plex-videos:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${MEDIA_HOST},nolock,soft,ro"
      device: ":/volume1/Media/Videos"