---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1028 # 'staff' user
      - PGID=50 # 'staff' group
      - TZ=America/Los_Angeles
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - sonarr-config:/config
      - sonarr-data:/data
    ports:
      - 8989:8989
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki

  sonarr-4k:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-4k
    restart: unless-stopped
    environment:
      - PUID=1028 # 'staff' user
      - PGID=50 # 'staff' group
      - TZ=America/Los_Angeles
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - sonarr-4k-config:/config
      - sonarr-data:/data
    ports:
      - 8990:8989
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki

volumes:
  sonarr-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/sonarr/config"

  sonarr-4k-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/sonarr-4k/config"

  sonarr-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${MEDIA_HOST},nolock,soft,rw"
      device: ":/volume1/Media"