---
services:
  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    restart: unless-stopped
    user: 1028:50
    environment:
      - PUID=1028 # 'staff' user
      - PGID=50 # 'staff' group
      - TZ=America/Los_Angeles
      - UN_LOG_FILE=/config/unpackerr.log
      - UN_RADARR_0_URL=https://radarr.${NETWORK_DOMAIN-bricksandblocks.net}
      - UN_RADARR_0_API_KEY=${RADARR_API_KEY}
      - UN_RADARR_1_URL=https://radarr-4k.${NETWORK_DOMAIN-bricksandblocks.net}
      - UN_RADARR_1_API_KEY=${RADARR_4K_API_KEY}
      - UN_SONARR_0_URL=https://sonarr.${NETWORK_DOMAIN-bricksandblocks.net}
      - UN_SONARR_0_API_KEY=${SONARR_API_KEY}
      - UN_SONARR_1_URL=https://sonarr-4k.${NETWORK_DOMAIN-bricksandblocks.net}
      - UN_SONARR_1_API_KEY=${SONARR_4K_API_KEY}
    volumes:
      - unpackerr-config:/config
      - unpackerr-data:/data
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki

volumes:
  unpackerr-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/unpackerr/config"

  unpackerr-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${MEDIA_HOST},nolock,soft,rw"
      device: ":/volume1/Media"