services:
  openttd:
    image: ghcr.io/ropenttd/openttd:latest
    container_name: openttd
    restart: unless-stopped
    environment:
      - loadgame=${OPENTTD_LOADGAME-exit}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 3979:3979/tcp
      - 3979:3979/udp
    volumes:
      - openttd-config:/config
    extends:
      file: ${ROOT_DIR-../../..}/lib/logging.yml
      service: logging-loki

volumes:
  openttd-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/openttd/config"