services:
  influxdb2:
    image: influxdb:2-alpine
    container_name: influxdb2
    restart: always
    volumes:
      - influxdb2-config:/etc/influxdb2
      - influxdb2-data:/var/lib/influxdb2
    ports:
      - 8086:8086

  chronograf:
    image: chronograf:alpine
    container_name: chronograf
    restart: always
    ports:
      - '8888:8888'
    volumes:
      - chronograf-data:/var/lib/chronograf
    depends_on:
      - influxdb2

volumes:
  chronograf-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/chronograf/data"

  influxdb2-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/influxdb2/config"

  influxdb2-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/influxdb2/data"