services:
  notifiarr:
    image: golift/notifiarr:latest
    container_name: notifiarr
    hostname: notifiarr
    restart: unless-stopped
    user: 1028:50 # UID=1028, 'staff' user, GID=50, 'staff' group
    security_opt: ['no-new-privileges:true']
    #environment:
      #- DN_API_KEY=${NOTIFIARR_API_KEY}
    ports:
      - "5454:5454"
    volumes:
      - ${LOCAL_PREFIX-/volume1/Docker}/notifiarr/config:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    logging:
      driver: loki
      options:
        loki-url: "http://loki.${NETWORK_DOMAIN-bricksandblocks.net}:3100/loki/api/v1/push"
        loki-retries: 5
        max-size: 100m
        mode: "non-blocking"