services:
  gluetun_protonvpn-wg:
    image: qmcgaw/gluetun:v3.41.1 # latest
    container_name: gluetun_protonvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - DNS_SERVER=on
      - LOG_LEVEL=${GLUETUN_LOG_LEVEL-error}
      - UPDATER_PERIOD=1h
      - UPDATER_VPN_SERVICE_PROVIDERS=protonvpn
      - VPN_PORT_FORWARDING=on
      - PORT_FORWARD_ONLY=on
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${GLUETUN_WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${GLUETUN_WIREGUARD_ADDRESSES}
      - VPN_INTERFACE_MTU=${GLUETUN_VPN_INTERFACE_MTU-1320}
      - SERVER_COUNTRIES=${GLUETUN_SERVER_COUNTRIES}
      # - BLOCK_MALICIOUS=off
      # - BLOCK_SURVEILLANCE=off
      # - BLOCK_ADS=off
    ports:
      - 49893:49893 # qbitorrent WebUI
      #- 6881:6881 # qbittorrent listening port for TCP
      #- 6881:6881/udp # qbittorrent listening port UDP
    volumes:
      - ${LOCAL_PREFIX-/volume1/Docker}/gluetun:/gluetun
    logging:
      driver: loki
      options:
        loki-url: "http://loki.${NETWORK_DOMAIN-bricksandblocks.net}:3100/loki/api/v1/push"
        loki-retries: 5
        max-size: 100m
        mode: "non-blocking"

  qbittorrent:
     image: lscr.io/linuxserver/qbittorrent:latest
     container_name: qbittorrent
     restart: unless-stopped
     network_mode: "service:gluetun_protonvpn-wg"
     depends_on:
       gluetun_protonvpn-wg:
         condition: service_started
     environment:
       - PUID=1028 # 'staff' user
       - PGID=50 # 'staff' group
       - DOCKER_MODS=ghcr.io/t-anc/gsp-qbittorent-gluetun-sync-port-mod:main
       - GSP_GTN_API_KEY=${GSP_GTN_API_KEY}
       - GSP_MINIMAL_LOGS=false
       #- TORRENTING_PORT="${QBITTORRENT_TOR_PORT}"
       - TZ=America/Los_Angeles
       - WEBUI_PORT=${QBITTORRENT_WEBUI-49893}
     volumes:
       - ${LOCAL_PREFIX-/volume1/Docker}/qbittorrent/config:/config
       - ${MEDIA_PREFIX-/volume1/Media}/downloads:/data/downloads
     logging:
       driver: loki
       options:
         loki-url: "http://loki.${NETWORK_DOMAIN-bricksandblocks.net}:3100/loki/api/v1/push"
         loki-retries: 5
         max-size: 100m
         mode: "non-blocking"
