services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1028 # 'staff' user
      - PGID=50 # 'staff' group
      - TZ=America/Los_Angeles
    volumes:
      - ${LOCAL_PREFIX-/volume1/Docker}/radarr/config:/config
    ports:
      - 7878:7878
    logging:
      driver: loki
      options:
        loki-url: "http://loki.${NETWORK_DOMAIN-bricksandblocks.net}:3100/loki/api/v1/push"
        loki-retries: 5
        max-size: 100m
        mode: "non-blocking"

  radarr-4k:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-4k
    restart: unless-stopped
    environment:
      - PUID=1028 # 'staff' user
      - PGID=50 # 'staff' group
      - TZ=America/Los_Angeles
    volumes:
      - ${LOCAL_PREFIX-/volume1/Docker}/radarr-4k/config:/config
    ports:
      - 7879:7878
    logging:
      driver: loki
      options:
        loki-url: "http://loki.${NETWORK_DOMAIN-bricksandblocks.net}:3100/loki/api/v1/push"
        loki-retries: 5
        max-size: 100m
        mode: "non-blocking"
