services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1028 # 'staff' user
      - PGID=50 # 'staff' group
      - TZ=America/Los_Angeles
    volumes:
      - ${LOCAL_PREFIX-/volume1/Docker}/sonarr/config:/config
      - ${MEDIA_PREFIX-/volume1/Media}:/data
    ports:
      - 8989:8989
    logging:
      driver: loki
      options:
        loki-url: "http://loki.${NETWORK_DOMAIN-bricksandblocks.net}:3100/loki/api/v1/push"
        loki-retries: 5
        max-size: 100m
        mode: "non-blocking"

  sonarr-4k:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-4k
    restart: unless-stopped
    environment:
      - PUID=1028 # 'staff' user
      - PGID=50 # 'staff' group
      - TZ=America/Los_Angeles
    volumes:
      - ${LOCAL_PREFIX-/volume1/Docker}/sonarr-4k/config:/config
      - ${MEDIA_PREFIX-/volume1/Media}:/data
    ports:
      - 8990:8989
    logging:
      driver: loki
      options:
        loki-url: "http://loki.${NETWORK_DOMAIN-bricksandblocks.net}:3100/loki/api/v1/push"
        loki-retries: 5
        max-size: 100m
        mode: "non-blocking"
