services:
 gluetun_protonvpn-ovpn:
   image: qmcgaw/gluetun:latest
   container_name: gluetun_protonvpn
   restart: unless-stopped
   cap_add:
     - NET_ADMIN
   devices:
     - /dev/net/tun:/dev/net/tun
   environment:
     - OPENVPN_USER=${GLUETUN_OVPN_USERNAME} # Add +pmp to the username
     - OPENVPN_PASSWORD=${GLUETUN_OVPN_PASSWORD}
     - VPN_PORT_FORWARDING=on
     - VPN_SERVICE_PROVIDER=protonvpn
     - SERVER_COUNTRIES=${GLUETUN_SERVER_COUNTRIES}
   ports:
     - 49893:49893 # qbitorrent WebUI
     #- 6881:6881 # qbittorrent listening port for TCP
     #- 6881:6881/udp # qbittorrent listening port UDP
   volumes:
     - gluetun-data:/gluetun
   extends:
     file: ${ROOT_DIR-..}/lib/logging.yml
     service: logging-loki

  # gluetun_protonvpn-wg:
  #   image: qmcgaw/gluetun:latest
  #   container_name: gluetun_protonvpn
  #   restart: unless-stopped
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   environment:
  #     - VPN_PORT_FORWARDING=on
  #     - VPN_SERVICE_PROVIDER=protonvpn
  #     - VPN_TYPE=wireguard
  #     - WIREGUARD_PRIVATE_KEY=${GLUETUN_WIREGUARD_PRIVATE_KEY}
  #     - WIREGUARD_ADDRESSES=${GLUETUN_WIREGUARD_ADDRESSES}
  #     # - WIREGUARD_MTU=1300
  #     - SERVER_COUNTRIES=${GLUETUN_SERVER_COUNTRIES}
  #     # - BLOCK_MALICIOUS=off
  #     # - BLOCK_SURVEILLANCE=off
  #     # - BLOCK_ADS=off
  #   ports:
  #     - 49893:49893 # qbitorrent WebUI
  #     #- 6881:6881 # qbittorrent listening port for TCP
  #     #- 6881:6881/udp # qbittorrent listening port UDP
  #   volumes:
  #     - gluetun-data:/gluetun
  #   extends:
  #     file: ${ROOT_DIR-../..}/lib/logging.yml
  #     service: logging-loki

volumes:
  gluetun-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/gluetun"