services:
  netbootxyz:
    image: netbootxyz/netbootxyz:latest
    container_name: netbootxyz
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      #- MENU_VERSION=1.9.9
    ports:
      - "69:69/udp"
      #- "3000:3000" # web interface
      #- "8007:80" # asset hosting
    labels:
      - "traefik.enable=true"
      # FIXME: these URLs are handled by local DNS to restrict traffic

      # web configuration interface
      - "traefik.http.routers.netbootxyz.rule=Host(`netbootxyz.${NETWORK_DOMAIN-bricksandblocks.net}`)"
      - "traefik.http.routers.netbootxyz.entrypoints=websecure"
      - "traefik.http.routers.netbootxyz.middlewares=internal-allowlist@file"
      - "traefik.http.routers.netbootxyz.tls=true"
      - "traefik.http.routers.netbootxyz.service=netbootxyz"
      - "traefik.http.services.netbootxyz.loadbalancer.server.port=3000"
      - "traefik.http.services.netbootxyz.loadbalancer.passhostheader=true"

      # asset hosting
      - "traefik.http.routers.netboot-assets.rule=Host(`netboot-assets.${NETWORK_DOMAIN-bricksandblocks.net}`)"
      - "traefik.http.routers.netboot-assets.entrypoints=websecure"
      - "traefik.http.routers.netboot-assets.middlewares=internal-allowlist@file"
      - "traefik.http.routers.netboot-assets.tls=true"
      - "traefik.http.routers.netboot-assets.service=netboot-assets"
      - "traefik.http.services.netboot-assets.loadbalancer.server.port=80"
      - "traefik.http.services.netboot-assets.loadbalancer.passhostheader=true"
    volumes:
      - netboot-config:/config
      - netboot-assets:/assets
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 3s

volumes:
  netboot-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/netbootxyz/config"

  netboot-assets:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/netbootxyz/assets"

