services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    environment:
      TZ: America/Los_Angeles
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_POLL_INTERVAL: 36000
    labels:
      - "com.centurylinklabs.watchtower.enable=true" # This label enables upgrades
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki