services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    privileged: true
    user: "telegraf:${DOCKER_GID-0}"
    hostname: "${HOSTNAME}"
    domainname: "${NETWORK_DOMAIN-bricksandblocks.net}"
    environment:
      TZ: America/Los_Angeles
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_POLL_INTERVAL: 36000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki