
services:
  wizarr:
    image: ghcr.io/wizarrrr/wizarr:latest
    container_name: wizarr
    restart: unless-stopped
    user: 1028:50 # UID=1028, 'staff' user, GID=50, 'staff' group
    ports:
      - "5690:5690"
    volumes:
      - wizarr-data:/data/database
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki

volumes:
  wizarr-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/wizarr/data"