services:
  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle_agent
    command: agent
    environment:
      - DOZZLE_HOSTNAME="${HOSTNAME}"
    ports:
      - 7007:7007
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    extends:
      file: ${ROOT_DIR-..}/lib/logging.yml
      service: logging-loki
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s