services:
  enigmabbs:
    image: enigmabbs/enigma-bbs:latest
    container_name: enigmabbs
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - enigmabbs:/enigma-bbs
      #- enigmabbs-mail:/mail
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki

volumes:
  enigmabbs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/enigmabbs"
