services:
  runner:
    image: gitea/act_runner:latest
    container_name: gitea-runner
    restart: unless-stopped
    environment:
      CONFIG_FILE: /data/config.yaml
      GITEA_INSTANCE_URL: "https://gitea.${NETWORK_DOMAIN-bricksandblocks.net}"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${GITEA_RUNNER_REGISTRATION_TOKEN}"
      GITEA_RUNNER_NAME: "gitea-runner-${HOSTNAME}"
      GITEA_RUNNER_LABELS: "${GITEA_RUNNER_LABELS}"
    volumes:
      - gitea-runner-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    extends:
      file: ${ROOT_DIR-..}/lib/logging.yml
      service: logging-loki

volumes:
  gitea-runner-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/${HOSTNAME}/gitea-runner"