services:
  palmr:
    image: kyantech/palmr:latest
    container_name: palmr
    restart: unless-stopped # Restart the container unless it is stopped
    user: "1028:50" # 'staff' user/group
    environment:
      - ENABLE_S3=false
      - ENCRYPTION_KEY=${PALMR_ENCRYPTION_KEY}
      - PALMR_UID=1028
      - PALMR_GID=50
      # S3 Configuration (only used when ENABLE_S3=true)
      # - ENABLE_S3=true # Set to true to use S3 storage
      # - S3_ENDPOINT=${S3_ENDPOINT} # S3 endpoint (you have to set this to the s3 endpoint of the s3 server) CHANGE THIS TO YOUR S3 ENDPOINT
      # - S3_USE_SSL=${S3_USE_SSL:-true} # Use ssl for the s3 server always true for s3
      # - S3_ACCESS_KEY=${S3_ACCESS_KEY} # S3 access key (you have to generate this key in s3 server)
      # - S3_SECRET_KEY=${S3_SECRET_KEY} # S3 secret key (you have to generate this key in s3 server)
      # - S3_REGION=${S3_REGION:-us-east-1} # S3 region (us-east-1 is the default region) but it depends on your s3 server region
      # - S3_BUCKET_NAME=${S3_BUCKET_NAME:-palmr-files} # Bucket name for the S3 storage (here we are using palmr-files as the bucket name to understand that this is the bucket for palmr)
      # - S3_FORCE_PATH_STYLE=false # For S3 compatibility we have to set this to false
      - SECURE_SITE=true
    ports:
      - "5487:5487" # Web port
      #- "3333:3333" # API port (OPTIONAL EXPOSED - ONLY IF YOU WANT TO ACCESS THE API DIRECTLY)
    volumes:
      - palmr-data:/app/server # Volume for the application data
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki

volumes:
  palmr-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/palmr"