services:
  p4d:
    image: frozenfoxx/p4d:latest
    container_name: p4d
    restart: always
    environment:
      - UID=1028 # 'staff' user
      - GID=50   # 'staff' group
    ports:
      - "1666:1666"
    volumes:
      - p4d-depots:/opt/perforce/depots
      - p4d-server:/opt/perforce/server
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki

volumes:
  p4d-server:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/p4d/server"

  p4d-depots:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/p4d/depots"