services:
  p4d:
    image: frozenfoxx/p4d:latest
    container_name: p4d
    restart: always
    environment:
      - UID=1028 # 'staff' user
      - GID=50
    ports:
      - "1666:1666"
    volumes:
      - p4d-depots:/opt/perforce/depots
      - ${LOCAL_PREFIX-/local}/p4d/server:/opt/perforce/server
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki
    healthcheck:
      test: ["CMD", "/usr/sbin/p4", "-p", "1666", "info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  # p4d-server:
  #   driver: local
  #   driver_opts:
  #     type: nfs
  #     o: "addr=${DATA_HOST},nolock,soft,rw"
  #     device: ":/volume1/Docker/p4d/server"

  p4d-depots:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw,nfsvers=4"
      device: ":/volume1/Docker/p4d/depots"