---
services:
  # Note: Pixelfed relies on a local .env file as part of the pixelfed deployment

  # HTTP/HTTPS proxy
  #
  # You can disable this service by setting [DOCKER_PROXY_PROFILE="disabled"]
  # in your [.env] file - the setting is near the bottom of the file.
  #
  # This also disables the [proxy-acme] service, if this is not desired, change the
  # [DOCKER_PROXY_ACME_PROFILE] setting to an empty string [""]
  #
  # See: https://github.com/nginx-proxy/nginx-proxy/tree/main/docs
  pixelfed-proxy:
    image: nginxproxy/nginx-proxy:1.7
    container_name: "${DOCKER_ALL_CONTAINER_NAME_PREFIX}-proxy"
    restart: unless-stopped
    profiles:
      - ${DOCKER_PROXY_PROFILE:-}
    environment:
      DOCKER_SERVICE_NAME: "pixelfed-proxy"
    volumes:
      - "${DOCKER_PROXY_HOST_DOCKER_SOCKET_PATH}:/tmp/docker.sock:ro"
      - "pixelfed-proxy-conf:/etc/nginx/conf.d"
      - "${DOCKER_ALL_HOST_CONFIG_ROOT_PATH}/proxy/vhost.d:/etc/nginx/vhost.d"
      - "${DOCKER_ALL_HOST_CONFIG_ROOT_PATH}/proxy/certs:/etc/nginx/certs"
      - "${DOCKER_ALL_HOST_DATA_ROOT_PATH}/proxy/html:/usr/share/nginx/html"
    ports:
      - "${DOCKER_PROXY_HOST_PORT_HTTP}:80"
      - "${DOCKER_PROXY_HOST_PORT_HTTPS}:443"
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki
    healthcheck:
      test: "curl --fail https://${APP_DOMAIN}/api/service/health-check"
      interval: "${DOCKER_PROXY_HEALTHCHECK_INTERVAL}"
      retries: 2
      timeout: 5s

  # Proxy companion for managing letsencrypt SSL certificates
  #
  # You can disable this service by setting [DOCKER_PROXY_ACME_PROFILE="disabled"]
  # in your [.env] file - the setting is near the bottom of the file.
  #
  # See: https://github.com/nginx-proxy/acme-companion/tree/main/docs
  proxy-acme:
    image: nginxproxy/acme-companion:2.6
    container_name: "${DOCKER_ALL_CONTAINER_NAME_PREFIX}-proxy-acme"
    restart: unless-stopped
    profiles:
      - ${DOCKER_PROXY_ACME_PROFILE:-}
    environment:
      DEBUG: 0
      DEFAULT_EMAIL: "${DOCKER_PROXY_LETSENCRYPT_EMAIL:?error}"
      NGINX_PROXY_CONTAINER: "${DOCKER_ALL_CONTAINER_NAME_PREFIX}-proxy"
    depends_on:
      - pixelfed-proxy
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki
    volumes:
      - "${DOCKER_ALL_HOST_CONFIG_ROOT_PATH}/proxy-acme:/etc/acme.sh"
      - "${DOCKER_ALL_HOST_CONFIG_ROOT_PATH}/proxy/certs:/etc/nginx/certs"
      - "pixelfed-proxy-conf:/etc/nginx/conf.d"
      - "${DOCKER_ALL_HOST_CONFIG_ROOT_PATH}/proxy/vhost.d:/etc/nginx/vhost.d"
      - "${DOCKER_ALL_HOST_DATA_ROOT_PATH}/proxy/html:/usr/share/nginx/html"
      - "${DOCKER_PROXY_HOST_DOCKER_SOCKET_PATH}:/var/run/docker.sock:ro"

  pixelfed-web:
    image: "${DOCKER_APP_IMAGE}:${DOCKER_APP_TAG}"
    container_name: "${DOCKER_ALL_CONTAINER_NAME_PREFIX}-web"
    restart: unless-stopped
    profiles:
      - ${DOCKER_WEB_PROFILE:-}
    build:
      dockerfile: docker/Dockerfile
      target: ${DOCKER_APP_RUNTIME}-runtime
      cache_from:
        - "type=registry,ref=${DOCKER_APP_IMAGE}:${DOCKER_APP_TAG}"
      args:
        APT_PACKAGES_EXTRA: "${DOCKER_APP_APT_PACKAGES_EXTRA:-}"
        BUILD_FRONTEND: "${DOCKER_APP_BUILD_FRONTEND:-0}"
        PHP_BASE_TYPE: "${DOCKER_APP_BASE_TYPE}"
        PHP_DEBIAN_RELEASE: "${DOCKER_APP_DEBIAN_RELEASE}"
        PHP_EXTENSIONS_EXTRA: "${DOCKER_APP_PHP_EXTENSIONS_EXTRA:-}"
        PHP_PECL_EXTENSIONS_EXTRA: "${DOCKER_APP_PHP_PECL_EXTENSIONS_EXTRA:-}"
        PHP_VERSION: "${DOCKER_APP_PHP_VERSION:?error}"
    environment:
      # Used by Pixelfed Docker init script
      DOCKER_SERVICE_NAME: "pixelfed-web"
      DOCKER_APP_ENTRYPOINT_DEBUG: ${DOCKER_APP_ENTRYPOINT_DEBUG:-0}
      ENTRYPOINT_SKIP_SCRIPTS: ${ENTRYPOINT_SKIP_SCRIPTS:-}
      # Used by [proxy] service
      LETSENCRYPT_HOST: "${DOCKER_PROXY_LETSENCRYPT_HOST}"
      LETSENCRYPT_EMAIL: "${DOCKER_PROXY_LETSENCRYPT_EMAIL:?error}"
      LETSENCRYPT_TEST: "${DOCKER_PROXY_LETSENCRYPT_TEST:-}"
      VIRTUAL_HOST: "${APP_DOMAIN}"
      VIRTUAL_PORT: "80"
    volumes:
      - "./.env:/var/www/.env"
      - "./.env.docker:/var/www/.env.docker"
      - "pixelfed-proxy-conf:/shared/proxy/conf.d"
      - "pixelfed-cache:/var/www/bootstrap/cache"
      - "${DOCKER_APP_HOST_OVERRIDES_PATH}:/docker/overrides:ro"
      - "pixelfed-storage:/var/www/storage"
    labels:
      com.github.nginx-proxy.nginx-proxy.keepalive: 30
      com.github.nginx-proxy.nginx-proxy.http2.enable: true
      com.github.nginx-proxy.nginx-proxy.http3.enable: true
    ports:
      - "${DOCKER_WEB_PORT_EXTERNAL_HTTP}:80"
    depends_on:
      - pixelfed-db
      - pixelfed-redis
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki
    healthcheck:
      test: 'curl --header "Host: ${APP_DOMAIN}" --fail http://localhost/api/service/health-check'
      interval: "${DOCKER_WEB_HEALTHCHECK_INTERVAL}"
      retries: 2
      timeout: 5s

  pixelfed-worker:
    image: "${DOCKER_APP_IMAGE}:${DOCKER_APP_TAG}"
    container_name: "${DOCKER_ALL_CONTAINER_NAME_PREFIX}-worker"
    command: gosu www-data php artisan horizon
    restart: unless-stopped
    stop_signal: SIGTERM
    profiles:
      - ${DOCKER_WORKER_PROFILE:-}
    build:
      dockerfile: docker/Dockerfile
      target: ${DOCKER_APP_RUNTIME}-runtime
      cache_from:
        - "type=registry,ref=${DOCKER_APP_IMAGE}:${DOCKER_APP_TAG}"
      args:
        APT_PACKAGES_EXTRA: "${DOCKER_APP_APT_PACKAGES_EXTRA:-}"
        BUILD_FRONTEND: "${DOCKER_APP_BUILD_FRONTEND:-0}"
        PHP_BASE_TYPE: "${DOCKER_APP_BASE_TYPE}"
        PHP_DEBIAN_RELEASE: "${DOCKER_APP_DEBIAN_RELEASE}"
        PHP_EXTENSIONS_EXTRA: "${DOCKER_APP_PHP_EXTENSIONS_EXTRA:-}"
        PHP_PECL_EXTENSIONS_EXTRA: "${DOCKER_APP_PHP_PECL_EXTENSIONS_EXTRA:-}"
        PHP_VERSION: "${DOCKER_APP_PHP_VERSION:?error}"
    environment:
      # Used by Pixelfed Docker init script
      DOCKER_SERVICE_NAME: "pixelfed-worker"
      DOCKER_APP_ENTRYPOINT_DEBUG: ${DOCKER_APP_ENTRYPOINT_DEBUG:-0}
      ENTRYPOINT_SKIP_SCRIPTS: ${ENTRYPOINT_SKIP_SCRIPTS:-}
    volumes:
      - "./.env:/var/www/.env"
      - "./.env.docker:/var/www/.env.docker"
      - "pixelfed-proxy-conf:/shared/proxy/conf.d"
      - "pixelfed-cache:/var/www/bootstrap/cache"
      - "${DOCKER_APP_HOST_OVERRIDES_PATH}:/docker/overrides:ro"
      - "pixelfed-storage:/var/www/storage"
    depends_on:
      - pixelfed-db
      - pixelfed-redis
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki
    healthcheck:
      test: gosu www-data php artisan horizon:status | grep running
      interval: "${DOCKER_WORKER_HEALTHCHECK_INTERVAL:?error}"
      timeout: 5s
      retries: 2

  pixelfed-cron:
    image: "${DOCKER_APP_IMAGE}:${DOCKER_APP_TAG}"
    container_name: "${DOCKER_ALL_CONTAINER_NAME_PREFIX}-cron"
    command: gosu www-data php artisan schedule:work -vvv
    restart: unless-stopped
    stop_signal: SIGTERM
    profiles:
      - ${DOCKER_CRON_PROFILE:-}
    build:
      dockerfile: docker/Dockerfile
      target: ${DOCKER_APP_RUNTIME}-runtime
      cache_from:
        - "type=registry,ref=${DOCKER_APP_IMAGE}:${DOCKER_APP_TAG}"
      args:
        APT_PACKAGES_EXTRA: "${DOCKER_APP_APT_PACKAGES_EXTRA:-}"
        BUILD_FRONTEND: "${DOCKER_APP_BUILD_FRONTEND:-0}"
        PHP_BASE_TYPE: "${DOCKER_APP_BASE_TYPE}"
        PHP_DEBIAN_RELEASE: "${DOCKER_APP_DEBIAN_RELEASE}"
        PHP_EXTENSIONS_EXTRA: "${DOCKER_APP_PHP_EXTENSIONS_EXTRA:-}"
        PHP_PECL_EXTENSIONS_EXTRA: "${DOCKER_APP_PHP_PECL_EXTENSIONS_EXTRA:-}"
        PHP_VERSION: "${DOCKER_APP_PHP_VERSION:?error}"
    environment:
      # Used by Pixelfed Docker init script
      DOCKER_SERVICE_NAME: "pixelfed-cron"
      DOCKER_APP_ENTRYPOINT_DEBUG: ${DOCKER_APP_ENTRYPOINT_DEBUG:-0}
      ENTRYPOINT_SKIP_SCRIPTS: ${ENTRYPOINT_SKIP_SCRIPTS:-}
    volumes:
      - "./.env:/var/www/.env"
      - "./.env.docker:/var/www/.env.docker"
      - "pixelfed-proxy-conf:/shared/proxy/conf.d"
      - "pixelfed-cache:/var/www/bootstrap/cache"
      - "${DOCKER_APP_HOST_OVERRIDES_PATH}:/docker/overrides:ro"
      - "pixelfed-storage:/var/www/storage"
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki
    depends_on:
      - pixelfed-db
      - pixelfed-redis

  pixelfed-db:
    image: ${DOCKER_DB_IMAGE:?error}
    container_name: "${DOCKER_ALL_CONTAINER_NAME_PREFIX}-db"
    command: ${DOCKER_DB_COMMAND:-}
    restart: unless-stopped
    profiles:
      - ${DOCKER_DB_PROFILE:-}
    environment:
      TZ: "${TZ:?error}"
      # MySQL (Oracle) - "Environment Variables" at https://hub.docker.com/_/mysql
      MYSQL_ROOT_PASSWORD: "${DOCKER_DB_ROOT_PASSWORD:?error}"
      MYSQL_USER: "${DB_USERNAME:?error}"
      MYSQL_PASSWORD: "${DB_PASSWORD:?error}"
      MYSQL_DATABASE: "${DB_DATABASE:?error}"
      # MySQL (MariaDB) - "Start a mariadb server instance with user, password and database" at https://hub.docker.com/_/mariadb
      MARIADB_ROOT_PASSWORD: "${DOCKER_DB_ROOT_PASSWORD:?error}"
      MARIADB_USER: "${DB_USERNAME:?error}"
      MARIADB_PASSWORD: "${DB_PASSWORD:?error}"
      MARIADB_DATABASE: "${DB_DATABASE:?error}"
      # PostgreSQL - "Environment Variables" at https://hub.docker.com/_/postgres
      POSTGRES_USER: "${DB_USERNAME:?error}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:?error}"
      POSTGRES_DB: "${DB_DATABASE:?error}"
    volumes:
      - "${DOCKER_DB_HOST_DATA_PATH:?error}:${DOCKER_DB_CONTAINER_DATA_PATH:?error}"
      # MySQL / MariaDB only
      - "${DOCKER_DB_HOST_CONFIG_PATH:?error}:/etc/mysql/conf.d/"
    ports:
      - "${DOCKER_DB_HOST_PORT:?error}:${DOCKER_DB_CONTAINER_PORT:?error}"
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: "${DOCKER_DB_HEALTHCHECK_INTERVAL:?error}"
      retries: 2
      timeout: 5s

  pixelfed-redis:
    image: redis:${DOCKER_REDIS_VERSION}
    container_name: "${DOCKER_ALL_CONTAINER_NAME_PREFIX}-redis"
    restart: unless-stopped
    command: "${DOCKER_REDIS_CONFIG_FILE:-} --requirepass '${REDIS_PASSWORD:-}'"
    profiles:
      - ${DOCKER_REDIS_PROFILE:-}
    environment:
      TZ: "${TZ:?error}"
      REDISCLI_AUTH: ${REDIS_PASSWORD:-}
    volumes:
      - "pixelfed-redis:/etc/redis"
      - "${DOCKER_REDIS_HOST_DATA_PATH}:/data"
    ports:
      - "${DOCKER_REDIS_HOST_PORT}:6379"
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: "${DOCKER_REDIS_HEALTHCHECK_INTERVAL:?error}"
      retries: 2
      timeout: 5s

volumes:
  pixelfed-cache:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/pixelfed/bootstrap/cache"

  pixelfed-storage:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/pixelfed/storage"

  pixelfed-db-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/pixelfed/db"

  pixelfed-proxy-conf:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/proxy/conf.d"

  pixelfed-redis:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/pixelfed/redis"