# networks:
#   searxng:

services:
  searxng-redis:
    image: docker.io/valkey/valkey:8-alpine
    container_name: searxng-redis
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    #networks:
    #  - searxng
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    volumes:
      - searxng-redis:/data
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki

  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    #networks:
    #  - searxng
    ports:
      - "9082:8080"
    environment:
      - SEARXNG_BASE_URL=https://searxng.${NETWORK_DOMAIN-bricksandblocks.net}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - searxng-config:/etc/searxng:rw
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki

volumes:
  searxng-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/searxng/config"

  searxng-redis:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/searxng/redis"