#networks:
#  gitea:
#    external: false

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-postgres:5432
      - GITEA__database__NAME=${GITEA_DATABASE_NAME-gitea}
      - GITEA__database__USER=${GITEA_DATABASE_USER}
      - GITEA__database__PASSWD=${GITEA_DATABASE_PASSWD}
#    networks:
#      - gitea
    ports:
      - "3000:3000"
      - "2022:22"
    #labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.gitea.rule=Host(`gitea.${NETWORK_DOMAIN-bricksandblocks.net}`)"
      #- "traefik.http.routers.gitea.entrypoints=websecure"
      #- "traefik.http.routers.gitea.tls.certresolver=letsencrypt"
      #- "traefik.http.routers.gitea.service=gitea"
      #- "traefik.http.services.gitea.loadbalancer.server.port=3000"
      #- "traefik.http.services.gitea.loadbalancer.server.scheme=http"
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    extends:
      file: ${ROOT_DIR-..}/lib/logging.yml
      service: logging-loki
    depends_on:
      gitea-postgres:
        condition: service_healthy

  gitea-postgres:
    image: postgres:15
    container_name: gitea-postgres
    restart: always
    environment:
      - POSTGRES_USER=${GITEA_DATABASE_USER}
      - POSTGRES_PASSWORD=${GITEA_DATABASE_PASSWD}
      - POSTGRES_DB=${GITEA_DATABASE_NAME-gitea}
#    networks:
#      - gitea
    volumes:
      - gitea-postgres-data:/var/lib/postgresql/data
    extends:
      file: ${ROOT_DIR-..}/lib/logging.yml
      service: logging-loki
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  gitea-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/gitea"

  gitea-postgres-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/gitea-postgres"