services:
  gluetun_protonvpn:
    image: qmcgaw/gluetun:latest
    container_name: gluetun_protonvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 49893:49893 # qbitorrent WebUI
      - 6081:6881 # qbittorrent listening port for TCP
      - 6081:6881/udp # qbittorrent listening port UDP
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${GLUETUN_WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${GLUETUN_WIREGUARD_ADDRESSES}
      - SERVER_COUNTRIES=${GLUETUN_SERVER_COUNTRIES}
    volumes:
      - ${DATA_PREFIX-/data}/gluetun:/gluetun
    restart: unless-stopped