services:
#  gluetun_protonvpn-ovpn:
#    image: qmcgaw/gluetun:latest
#    container_name: gluetun_protonvpn
#    cap_add:
#      - NET_ADMIN
#    devices:
#      - /dev/net/tun:/dev/net/tun
#    ports:
#      - 49893:49893 # qbitorrent WebUI
      #- 6881:6881 # qbittorrent listening port for TCP
      #- 6881:6881/udp # qbittorrent listening port UDP
#    environment:
#      - OPENVPN_USER=${GLUETUN_OVPN_USERNAME} # Add +pmp to the username
#      - OPENVPN_PASSWORD=${GLUETUN_OVPN_PASSWORD}
#      - VPN_PORT_FORWARDING=on
#      - VPN_SERVICE_PROVIDER=protonvpn
#      - SERVER_COUNTRIES=${GLUETUN_SERVER_COUNTRIES}
#    volumes:
#      - gluetun-data:/gluetun
#    restart: unless-stopped

  gluetun_protonvpn-wg:
    image: qmcgaw/gluetun:latest
    container_name: gluetun_protonvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 49893:49893 # qbitorrent WebUI
      #- 6881:6881 # qbittorrent listening port for TCP
      #- 6881:6881/udp # qbittorrent listening port UDP
    environment:
      - VPN_PORT_FORWARDING=on
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${GLUETUN_WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${GLUETUN_WIREGUARD_ADDRESSES}
      - SERVER_COUNTRIES=${GLUETUN_SERVER_COUNTRIES}
    volumes:
      - gluetun-data:/gluetun
    restart: unless-stopped

volumes:
  gluetun-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/gluetun"