services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
    volumes:
      - heimdall-data:/config
    #ports:
    #  - 443:443
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.${NETWORK_DOMAIN-bricksandblocks.net}`)"
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      - "traefik.http.routers.heimdall.tls.certresolver=letsencrypt"
      - "traefik.http.routers.heimdall.service=heimdall"
      #- "traefik.http.routers.heimdall.middlewares=internal-allowlist@file"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
      - "traefik.http.services.heimdall.loadbalancer.server.scheme=http"
    logging: *logging-loki

volumes:
  heimdall-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/heimdall"