services:
  influxdb2:
    image: influxdb:2-alpine
    container_name: influxdb2
    restart: always
    volumes:
      - influxdb-config:/etc/influxdb2
      - influxdb-data:/var/lib/influxdb2
    ports:
      - 8086:8086

volumes:
  influxdb2-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/influxdb2/config"

  influxdb2-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/influxdb2/data"