---
services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - kavita-data:/config
      - kavita-library:/data:ro
    ports:
      - 5000:5000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kavita.rule=Host(`kavita.${NETWORK_DOMAIN-bricksandblocks.net}`)"
      - "traefik.http.routers.kavita.entrypoints=websecure"
      - "traefik.http.routers.kavita.tls.certresolver=letsencrypt"
      - "traefik.http.routers.kavita.service=kavita"
      #- "traefik.http.routers.kavita.middlewares=foxhole@docker"
      - "traefik.http.services.kavita.loadbalancer.server.port=5000"
      - "traefik.http.services.kavita.loadbalancer.server.scheme=http"

volumes:
  kavita-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/kavita"

  kavita-library:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${MEDIA_HOST},nolock,soft,ro"
      device: ":/volume1/Documents/KavitaLibrary"