services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    environment:
      - LOKI_CONFIG_FILE=/etc/loki/loki-config.yaml
    volumes:
      - loki-config:/etc/loki
      - loki-data:/loki
    ports:
      - "3100:3100"

volumes:
  loki-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/loki/config"

  loki-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/loki/data"