services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: always
    deploy:
      resources:
        limits:
          memory: 1000M
    environment:
      ALLOW_SIGNUP: false
      BASE_URL: https://mealie.${NETWORK_DOMAIN-bricksandblocks.net}
      #LOG_LEVEL: debug
      MAX_WORKERS: 1
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      WEB_CONCURRENCY: 1
      # Database Settings
      DB_ENGINE: postgres
      PG_USER: ${MEALIE_PG_USER}
      POSTGRES_USER: ${MEALIE_PG_USER}
      POSTGRES_PASSWORD: ${MEALIE_PG_PASSWORD}
      POSTGRES_SERVER: mealie-postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      #- "traefik.enable=true"
      #- "traefik.http.routers.mealie.rule=Host(`mealie.${NETWORK_DOMAIN-bricksandblocks.net}`)"
      #- "traefik.http.routers.mealie.entrypoints=websecure"
      #- "traefik.http.routers.mealie.tls.certresolver=letsencrypt"
      #- "traefik.http.routers.mealie.service=mealie"
      #- "traefik.http.services.mealie.loadbalancer.server.port=9000"
      #- "traefik.http.services.mealie.loadbalancer.server.scheme=http"
    ports:
        - "9925:9000"
    volumes:
      - mealie-data:/app/data/
    extends:
      file: ${ROOT_DIR-..}/lib/logging.yml
      service: logging-loki
    depends_on:
      mealie-postgres:
        condition: service_healthy

  mealie-postgres:
    image: postgres:15
    container_name: mealie-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${MEALIE_PG_PASSWORD}
      POSTGRES_USER: ${MEALIE_PG_USER}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - mealie-postgres-data:/var/lib/postgresql/data
    extends:
      file: ${ROOT_DIR-..}/lib/logging.yml
      service: logging-loki
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mealie-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/mealie"

  mealie-postgres-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/mealie-postgres"