services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: always
    environment:
      - -INSTALL4J_ADD_VM_PARAMS="-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-license"
    ports:
      #- "9081:8081"
      - "${NEXUS_DOCKER_PORT-9081}:${NEXUS_DOCKER_PORT-9081}"
    volumes:
      - nexus-data:/nexus-data
      - nexus-license:/nexus-license
    labels:
      - "traefik.enable=true"

      # Default registries
      - "traefik.http.routers.nexus.rule=Host(`nexus.${NETWORK_DOMAIN-bricksandblocks.net}`)"
      - "traefik.http.routers.nexus.entrypoints=websecure"
      - "traefik.http.routers.nexus.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nexus.service=nexus"
      - "traefik.http.services.nexus.loadbalancer.server.port=8081"
      - "traefik.http.services.nexus.loadbalancer.server.scheme=http"

      # Docker
      - "traefik.http.routers.nexus-docker.rule=Host(`docker.${NETWORK_DOMAIN-bricksandblocks.net}`)"
      - "traefik.http.routers.nexus-docker.entrypoints=websecure"
      - "traefik.http.routers.nexus-docker.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nexus-docker.service=docker-registry-service"
      - "traefik.http.services.docker-registry-service.loadbalancer.server.port=${NEXUS_DOCKER_PORT-9081}"

volumes:
  nexus-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/nexus/data"

  nexus-license:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/nexus/license"