x-web-defaults: &web-defaults
  restart: unless-stopped
  build:
    context: backend
    dockerfile: 'Dockerfile'
  volumes:
    - ./backend:/app
    - ./frontend:/frontend
  depends_on:
    - obico-dragonfly
  environment:
    OCTOPRINT_TUNNEL_PORT_RANGE: '0-0'
    EMAIL_HOST: '${OBICO_EMAIL_HOST-}'
    EMAIL_HOST_USER: '${OBICO_EMAIL_HOST_USER-}'
    EMAIL_HOST_PASSWORD: '${OBICO_EMAIL_HOST_PASSWORD-}'
    EMAIL_PORT: '${OBICO_EMAIL_PORT-587}'
    EMAIL_USE_TLS: '${OBICO_EMAIL_USE_TLS-True}'
    DEFAULT_FROM_EMAIL: '${OBICO_DEFAULT_FROM_EMAIL-changeme@example.com}'
    DEBUG: '${OBICO_DEBUG-False}'    # Don't set DEBUG to True unless you know what you are doing. Otherwise the static files will be cached in browser until hard-refresh
    ADMIN_IP_WHITELIST: '${OBICO_ADMIN_IP_WHITELIST-}'
    SITE_USES_HTTPS: '${OBICO_SITE_USES_HTTPS-False}'
    SITE_IS_PUBLIC: '${OBICO_SITE_IS_PUBLIC-False}'
    CSRF_TRUSTED_ORIGINS: '${OBICO_CSRF_TRUSTED_ORIGINS-}'
    SOCIAL_LOGIN: '${OBICO_SOCIAL_LOGIN-False}'
    REDIS_URL: 'redis://obico-dragonfly:6379'
    DATABASE_URL: '${OBICO_DATABASE_URL-sqlite:////app/db.sqlite3}'
    INTERNAL_MEDIA_HOST: '${OBICO_INTERNAL_MEDIA_HOST-http://web:3334}'
    ML_API_HOST: '${OBICO_ML_API_HOST-http://ml_api:3333}'
    ACCOUNT_ALLOW_SIGN_UP: '${OBICO_ACCOUNT_ALLOW_SIGN_UP-False}'
    WEBPACK_LOADER_ENABLED: '${OBICO_WEBPACK_LOADER_ENABLED-False}'
    TELEGRAM_BOT_TOKEN: '${OBICO_TELEGRAM_BOT_TOKEN-}'
    TWILIO_ACCOUNT_SID: '${OBICO_TWILIO_ACCOUNT_SID-}'
    TWILIO_AUTH_TOKEN: '${OBICO_TWILIO_AUTH_TOKEN-}'
    TWILIO_FROM_NUMBER: '${OBICO_TWILIO_FROM_NUMBER-}'
    SENTRY_DSN: '${OBICO_SENTRY_DSN-}'
    PUSHOVER_APP_TOKEN: '${OBICO_PUSHOVER_APP_TOKEN-}'
    SLACK_CLIENT_ID: '${OBICO_SLACK_CLIENT_ID-}'
    SLACK_CLIENT_SECRET: '${OBICO_SLACK_CLIENT_SECRET-}'
    DJANGO_SECRET_KEY: '${OBICO_DJANGO_SECRET_KEY-}'
    SYNDICATE: '${OBICO_SYNDICATE-}'
    VERSION:

services:
  ml_api:
    hostname: ml_api
    restart: unless-stopped
    build:
      context: ml_api
    environment:
      DEBUG: 'True'
      FLASK_APP: 'server.py'
      # ML_API_TOKEN:
    tty: true
    command: bash -c "gunicorn --bind 0.0.0.0:3333 --workers 1 wsgi"

  web:
    <<: *web-defaults
    hostname: web
    ports:
      - "3334:3334"
    depends_on:
      - ml_api
    command: sh -c 'python manage.py migrate && python manage.py collectstatic -v 2 --noinput && daphne -b 0.0.0.0 -p 3334 config.routing:application'

  tasks:
    <<: *web-defaults
    hostname: tasks
    command: sh -c "celery -A config worker --beat -l info -c 2 -Q realtime,celery"

  obico-dragonfly:
    restart: unless-stopped
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'