---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM} #optional
    volumes:
      - ${DATA_PREFIX-/data}/plex/config:/config
      - ${MEDIA_PREFIX-/mnt}/Music:/data/Music:ro
      - ${MEDIA_PREFIX-/mnt}/Videos:/data/Videos:ro
    restart: unless-stopped