networks:
  prometheus:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
      - '--storage.tsdb.retention.time=7d'
    volumes:
      - prometheus-config:/etc/prometheus
      #- prometheus-data:/data  #FIXME: disabled due to NFS being unsupported
    ports:
      - "9090:9090"
    networks:
      - prometheus

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    networks:
      - prometheus
    ports:
      - "9100:9100"

  alert-manager:
    image: prom/alertmanager
    container_name: alert-manager
    restart: always
    volumes:
      - alertmanager-config:/alertmanager
    networks:
      - prometheus
    ports:
      - "9093:9093"

volumes:
  alertmanager-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,ro"
      device: ":/volume1/Docker/alertmanager/config"

  prometheus-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,ro"
      device: ":/volume1/Docker/prometheus/config"

  prometheus-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/prometheus/data"
