services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TORRENTING_PORT=6881
      - TZ=America/Los_Angeles
      - WEBUI_PORT="${QBITTORRENT_WEBUI-49893}"
    volumes:
      - ${DATA_PREFIX-/data}/qbittorrent/config:/config
      - ${DATA_PREFIX-/data}/qbittorrent/downloads:/downloads
    network_mode: "container:gluetun_protonvpn"
    #ports:
      #- 6081:6881
      #- 6081:6881/udp
      #- "${QBITTORRENT_WEBUI-49893}:${QBITTORRENT_WEBUI-49893}"
    restart: unless-stopped