services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: "container:gluetun_protonvpn"
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_MODS=ghcr.io/t-anc/gsp-qbittorent-gluetun-sync-port-mod:main
      - GSP_GTN_API_KEY=${GSP_GTN_API_KEY}
      - GSP_MINIMAL_LOGS=false
      #- TORRENTING_PORT="${QBITTORRENT_TOR_PORT}"
      - TZ=America/Los_Angeles
      - WEBUI_PORT=${QBITTORRENT_WEBUI-49893}
    volumes:
      - qbittorrent-data:/config
      - qbittorrent-downloads:/downloads
    extends:
      file: ${ROOT_DIR-..}/lib/logging.yml
      service: logging-loki

volumes:
  qbittorrent-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/qbittorrent/config"

  qbittorrent-downloads:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/qbittorrent/downloads"