services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TORRENTING_PORT="${QBITTORRENT_TOR_PORT}"
      - TZ=America/Los_Angeles
      - WEBUI_PORT="${QBITTORRENT_WEBUI-49893}"
    volumes:
      - ${DATA_PREFIX-/data}/qbittorrent/config:/config
      - ${DATA_PREFIX-/data}/qbittorrent/downloads:/downloads
    network_mode: "container:gluetun_protonvpn-ovpn"
    restart: unless-stopped
