services:
  unpoller:
    image: ghcr.io/unpoller/unpoller:latest
    container_name: unpoller
    restart: always
    environment:
      UP_POLLER_DEBUG: "false"

      # UniFi Variables
      UP_UNIFI_DEFAULT_SAVE_ALARMS: "true"
      UP_UNIFI_DEFAULT_SAVE_ANOMALIES: "true"
      UP_UNIFI_DEFAULT_SAVE_DPI: "true"
      UP_UNIFI_DEFAULT_SAVE_EVENTS: "true"
      UP_UNIFI_DEFAULT_SAVE_IDS: "true"
      UP_UNIFI_DEFAULT_SAVE_SITES: "true"
      UP_UNIFI_DEFAULT_URL: "${UNPOLLER_URL}"
      UP_UNIFI_DEFAULT_USER: "${UNPOLLER_USER}"
      UP_UNIFI_DEFAULT_PASS: "${UNPOLLER_PASSWORD}"

      # Loki Variables
      UP_LOKI_DISABLE: "false"
      UP_LOKI_URL: "https://loki.${NETWORK_DOMAIN-bricksandblocks.net}"

      # Prometheus Variables
      UP_PROMETHEUS_NAMESPACE: "unpoller"
      UP_PROMETHEUS_HTTP_LISTEN: "0.0.0.0:9130"

      # InfluxDB Variables
      #INFLUXDB_DB: "${UNPOLLER_INFLUXDB_DB}"
      UP_INFLUXDB_DISABLE: "true"
      #UP_INFLUXDB_USER: "${UNPOLLER_INFLUXDB_USER}"
      #UP_INFLUXDB_PASS: "${UNPOLLER_INFLUXDB_PASSWORD}"
      #UP_INFLUXDB_ORG: "${UNPOLLER_INFLUXDB_ORG}"
      #UP_INFLUXDB_BUCKET: "${UNPOLLER_INFLUXDB_BUCKET}"
      #UP_INFLUXDB_AUTH_TOKEN: "${UNPOLLER_INFLUXDB_TOKEN}"
      #UP_INFLUXDB_URL: "https://influxdb.${NETWORK_DOMAIN-bricksandblocks.net}"
    ports:
      - 9130:9130/tcp
    extends:
      file: ${ROOT_DIR-..}/lib/logging.yml
      service: logging-loki
