services:
  vector:
    image: timberio/vector:latest-alpine
    container_name: vector
    restart: always
    hostname: "${HOSTNAME}"
    domainname: "${NETWORK_DOMAIN-bricksandblocks.net}"
    #ports:
      #- "127.0.0.1:5123:5123/udp" # Syslog, localhost only
      #- "5123:5123" # Syslog
      #- "8686:8686" # API, default disabled
      #- "9598:9598" # Prometheus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vector-config:/etc/vector:ro
    extends:
      file: ${ROOT_DIR-..}/lib/logging.yml
      service: logging-loki

volumes:
  vector-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,ro"
      device: ":/volume1/Docker/vector/config"
