services:
  vrising:
    image: trueosiris/vrising
    container_name: vrising
    ports:
      - '9876:9876/udp'
      - '9877:9877/udp'
    environment:
      - TZ=America/Los_Angeles
      - SERVERNAME=${VRISING_SERVERNAME-Cult of Foxx - PVE}
    restart: unless-stopped
    volumes:
      - vrising-persistent-data:/mnt/vrising/persistentdata
      - vrising-server-data:/mnt/vrising/server
    network_mode: bridge

volumes:
  vrising-persistent-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/vrising/presistentdata"

  vrising-server-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/vrising/server"