#networks:
#  zandronum:
#    external: true

services:
  zandronum-stream:
    image: rcdailey/zandronum-server:official-latest
    container_name: zandronum-stream
    network: host
    restart: always
    volumes:
      - zandronum-wads:/wads:ro
      - zandronum-configs:/configs:ro
    command: >
      -port 10667
      -iwad /wads/DOOM2.WAD
      -file /wads/maps/Valiant/Valiant.wad
      -file /wads/mods/brutalv21.pk3
      +exec /configs/global.cfg
      +exec /configs/coop.cfg
      +exec /configs/maps_doom2.cfg
      +sv_hostname "Cult of Foxx"

  #lexicon:
  #  image: rcdailey/zandronum-server:official-latest
  #  container_name: doom-lexicon
  #  network: host
  #  restart: always
  #  volumes:
  #    - ${DATA_PREFIX-/data}/zandronum/wads:/data:ro
  #    - ${DATA_PREFIX-/data}/zandronum/configs:/configs:ro
  #  command: >
  #    -port 10668
  #    -iwad /wads/DOOM2.WAD
  #    -file /data/pretend_sentinels_lexicon.pk3
  #    +exec /configs/global.cfg
  #    +exec /configs/coop.cfg
  #    +sv_hostname "The Sentinel Lexicon Server"
  #    +map VR
  #    +lexicon_timer_start 60

volumes:
  zandronum-configs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,ro"
      device: ":/volume1/Docker/zandronum/configs"

  zandronum-wads:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,ro"
      device: ":/volume1/Docker/zandronum/wads"