services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    hostname: ${HOSTNAME}
    privileged: true
    command:
    - '--port=8091'
    - '--docker_only=true'
    - '--housekeeping_interval=15s'
    - '--enable_metrics=app,cpu,diskIO,memory,network,process'
    #- '--store_container_labels=false'
    #- '--whitelisted_container_labels=org.label-schema.group,com.docker.compose.project,com.docker.compose.service'
    environment:
      CADVISOR_HEALTHCHECK_URL: "http://${HOSTNAME}:8091/healthz"
    ports:
      - "8091:8091"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki
    #healthcheck:
      #disable: true