services:
  node-exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: always
    command:
      - '--path.rootfs=/host'
    cap_add:
      - SYS_TIME
    pid: host
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "9100:9100"
    volumes:
      - '/:/host:ro,rslave'
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki