#networks:
#  zandronum:
#    external: true

services:
  zandronum-stream:
    image: rcdailey/zandronum-server:official-latest
    container_name: zandronum-stream
    network_mode: host
    restart: always
    volumes:
      - zandronum-wads:/wads:ro
      - zandronum-configs:/configs:ro
    command: >
      -port 10666
      -iwad /wads/DOOM2.WAD
      -file /wads/maps/Lexicon/lexicon-beta-build-133.pk3
      -file /wads/maps/Lexicon/lexicon-miscdata-beta-build-133.pk3
      +exec /configs/global.cfg
      +exec /configs/coop.cfg
      +sv_hostname "Cult of Foxx"
      +map VR
      +lexicon_timer_start 60

volumes:
  zandronum-configs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,ro"
      device: ":/volume1/Docker/zandronum/configs"

  zandronum-wads:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,ro"
      device: ":/volume1/Docker/zandronum/wads"