#networks:
#  zandronum:
#    external: true

services:
  zandronum:
    image: rcdailey/zandronum-server:official-latest
    container_name: zandronum
    network_mode: host
    hostname: "zandronum"
    domainname: "${NETWORK_DOMAIN-bricksandblocks.net}"
    restart: always
    volumes:
      - zandronum-wads:/wads:ro
      - zandronum-configs:/configs:ro
    command: >
      -port 10666
      -iwad /wads/DOOM2.WAD
      -file /wads/maps/Valiant/Valiant.wad
      -file /wads/mods/brutalv21.pk3
      +exec /configs/global.cfg
      +exec /configs/coop.cfg
      +exec /configs/maps_valiant.cfg
      +sv_hostname "Cult of Foxx"

volumes:
  zandronum-configs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,ro"
      device: ":/volume1/Docker/zandronum/configs"

  zandronum-wads:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,ro"
      device: ":/volume1/Docker/zandronum/wads"