services:
  foundryvtt:
    #image: felddy/foundryvtt:release # Latest
    image: felddy/foundryvtt:release-13.348.0
    container_name: foundryvtt
    restart: unless-stopped
    hostname: "${HOSTNAME}"
    #FIXME: https://github.com/felddy/foundryvtt-docker/issues/56
    #user: "1028:50" # 'staff' user/group
    environment:
      CONTAINER_PRESERVE_CONFIG: ${FOUNDRYVTT_CONTAINER_PRESERVE_CONFIG-true}
      FOUNDRY_HOSTNAME: "https://foundryvtt.${NETWORK_DOMAIN-bricksandblocks.net}"
      FOUNDRY_PASSWORD: ${FOUNDRYVTT_PASSWORD}
      FOUNDRY_PROXY_PORT: ${FOUNDRYVTT_PROXY_PORT-443}
      FOUNDRY_PROXY_SSL: ${FOUNDRYVTT_PROXY_SSL-true}
      FOUNDRY_TELEMETRY: ${FOUNDRYVTT_TELEMETRY-true}
      FOUNDRY_USERNAME: ${FOUNDRYVTT_USERNAME}
      TIMEZONE: "America/Los_Angeles"
    ports:
      - "30032:30000"
    volumes:
      - foundryvtt-data:/data/
    extends:
      file: ${ROOT_DIR-../..}/lib/logging.yml
      service: logging-loki

volumes:
  foundryvtt-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,rw"
      device: ":/volume1/Docker/foundryvtt/data"