#networks:
#  zandronum:
#    external: true

services:
  zandronum:
    image: rcdailey/zandronum-server:official-latest
    container_name: zandronum
    network_mode: host
    hostname: "zandronum"
    domainname: "${NETWORK_DOMAIN-bricksandblocks.net}"
    restart: unless-stopped
    command: >
      +sv_hostname "${ZANDRONUM_HOSTNAME-Cult of Foxx}"
      -port ${ZANDRONUM_PORT-10666}
      ${ZANDRONUM_COMMAND}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - zandronum-wads:/wads:ro
      - zandronum-configs:/configs:ro
    extends:
      file: ${ROOT_DIR-../../..}/lib/logging.yml
      service: logging-loki

volumes:
  zandronum-configs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,ro"
      device: ":/volume1/Docker/zandronum/configs"

  zandronum-wads:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${DATA_HOST},nolock,soft,ro"
      device: ":/volume1/Docker/zandronum/wads"